### ISSUE TITLE
replace Essay youtube clip links with new youtube-clip-modal.html include

### ISSUE THREAD

**Issue by evanwill** [uidaholib/mainstreetvideo_source#3]
@aweymo-ui is working on this in branch modal-clips

new include:
{% include feature/youtube-clip-modal.html text="example" objectid="demo01" start="" %}
https://github.com/uidaholib/mainstreetvideo_source/blob/main/_includes/feature/youtube-clip-modal.html

replace all youtube links in the essays (cult-classics.md, essay-intro.md, horror.md, westerns.md) that are clips, with the new include instead.
If the link is actually to a mainstreet interview, find the item objectid and use that instead of the link.

e.g. 
the old link `["browse and wonder"](https://youtu.be/M44t7fyKxSA?t=1306){:target='_blank'}`
becomes include `{% include feature/youtube-clip-modal.html text='"browse and wonder"' objectid="mainstreet015" start="1306" %}`

**Comment by aweymo-ui** [comment]
This request is complete except for the blockquote items you told me to skip: https://github.com/uidaholib/mainstreetvideo_source/tree/modal-clips
